data:extend({
    {
        type = "int-setting",
        name = "chat_emoji_gui_emoji_size",
        setting_type = "startup",
        default_value = 128,
        minimum_value = 16,
        maximum_value = 512,
        order = "a",
    },
    {
        type = "int-setting",
        name = "chat_emoji_gui_emoji_table",
        setting_type = "runtime-per-user",
        default_value = 6,
        minimum_value = 1,
        maximum_value = 100,
        order = "a",
    },
    {
        type = "int-setting",
        name = "chat_emoji_gui_emoji_table_horizontal_spacing",
        setting_type = "runtime-per-user",
        default_value = 10,
        minimum_value = 0,
        maximum_value = 100,
        order = "b",
    },
    {
        type = "int-setting",
        name = "chat_emoji_gui_emoji_table_vertical_spacing",
        setting_type = "runtime-per-user",
        default_value = 10,
        minimum_value = 0,
        maximum_value = 100,
        order = "c",
    },
    {
        type = "int-setting",
        name = "chat_emoji_gui_emoji_scroll_pane_height_max",
        setting_type = "runtime-per-user",
        default_value = 500,
        minimum_value = 100,
        maximum_value = 1000,
        order = "d",
    },
    {
        type = "int-setting",
        name = "chat_emoji_gui_emoji_scroll_pane_height_min",
        setting_type = "runtime-per-user",
        default_value = 50,
        minimum_value = 16,
        maximum_value = 1000,
        order = "e",
    },
    {
        type = "int-setting",
        name = "chat_emoji_gui_emoji_scroll_pane_height_min",
        setting_type = "runtime-per-user",
        default_value = 50,
        minimum_value = 16,
        maximum_value = 1000,
        order = "e",
    },
    {
        type = "bool-setting",
        name = "chat_emoji_startup_log_activate",
        setting_type = "startup",
        default_value = false,
        order = "b",
    }
})
